include("../src/parameters.jl")
include("../src/setup.jl")
include("../src/drive.jl")
include("../src/thermal.jl")

fortran = readlines("../fortran/data/test_thermal.txt")

Ds1_fortran = parse.(Float64,split(fortran[1]))
gs1_fortran = parse.(Float64,split(fortran[2]))
ks1_fortran = parse.(Float64,split(fortran[3]))
Ts1_fortran = parse.(Float64,split(fortran[4]))
Tveg0_fortran = parse.(Float64,split(fortran[5]))
csoil_fortran = parse.(Float64,split(fortran[6]))
ksnow_fortran = parse.(Float64,split(fortran[7]))
ksoil_fortran = parse.(Float64,split(fortran[8]))

println(maximum(abs.(Ds1_fortran - Ds1)))
println(maximum(abs.(gs1_fortran - gs1)))
println(maximum(abs.(ks1_fortran - ks1)))
println(maximum(abs.(Ts1_fortran - Ts1)))
println(maximum(abs.(Tveg0_fortran - Tveg0)))
println(maximum(abs.(csoil_fortran - csoil[:,1,1])))
println(maximum(abs.(ksnow_fortran - ksnow[:,1,1])))
println(maximum(abs.(ksoil_fortran - ksoil[:,1,1])))