const cp = 1005         # Specific heat capacity of air (J/K/kg)
const eps_fsm = 0.622       # Ratio of molecular weights of water and dry air
const e0 = 610.78       # Saturation vapour pressure at Tm (Pa)
const grav = 9.81       # Acceleration due to gravity (m/s^2)
const hcap_ice = 2100   # Specific heat capacity of ice (J/K/kg)
const hcap_wat = 4180   # Specific heat capacity of water (J/K/kg)
const hcon_air = 0.025  # Thermal conductivity of air (W/m/K)
const hcon_clay = 1.16  # Thermal conductivity of clay (W/m/K)
const hcon_ice = 2.24   # Thermal conducivity of ice (W/m/K)
const hcon_sand = 1.57  # Thermal conductivity of sand (W/m/K)
const hcon_wat = 0.56   # Thermal conductivity of water (W/m/K)
const I0 = 1367         # Solar constant (W/m^2)
const Lf = 0.334e6      # Latent heat of fusion (J/kg)
const Lv = 2.501e6      # Latent heat of vapourisation (J/kg)
const Ls = Lf + Lv      # Latent heat of sublimation (J/kg)
const pi = 3.14159      # pi
const Rair = 287        # Gas constant for air (J/K/kg)
const Rwat = 462        # Gas constant for water vapour (J/K/kg)
const rho_ice = 917     # Density of ice (kg/m^3)
const rho_wat = 1000    # Density of water (kg/m^3)
const sb = 5.67e-8      # Stefan-Boltzmann constant (W/m^2/K^4)
const em_snow = 0.99    # Emissivity snow for Stefan-Boltzmann
const em_soil = 0.90    # Emissivity soil for Stefan-Boltzmann
const Tm = 273.15       # Melting point (K)
const vkman = 0.4       # Von Karman constant